# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:xbDScaSNLioLLafGRHcAeZSw3T/Y6slWPiCsPX3v9Iih2+Dkna/qc4PDSnYZlzUbnmNLhKLuyORrCWxSvtvSEqkuMTFeYLLeJhDictp3RPy9oEPDlU5dCVwxIq3R58sQhVruL2m4d1OJoyIO1K3ZhHSutIsxIPQBc9cvFfG3lEszRhan16NgED4nie2fi/02RvBiucyQo6RTgqYssEydwWeOFQNILrQJTmRc0ntY8mmKPLJ1,iv:mu50BNs3zjWc+4dYZoYv4katSPDPriqGZ6tyvslTze4=,tag:zTszM4XMCkUX/Dq8LqB8Mg==,type:str]
sops:
  age:
    - recipient: age1205h2v4h4rvx0hfew4uemlrfjnnpfccxj7l9r2ycxdcc92r48dksefc88c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N21YRllFdVFGTW1IUHAv
        OUVoZG1jcmdFY0ErdjQwRzRiQzEwdnV1YzFFCktuN0Q3b1N6WE5TZEUrUnZOQmRa
        WFlpUWgzZ2hIVUZuZWlkRDluOTREcGsKLS0tIE9SNER3NHJDM3NON2VkVGpTeW02
        V2xIaHhRbEEzZHlXQkYwMEVLcCtSSFUKWaKfXYYBM/I1PMTPXmSYzEa6Dd3ejSBz
        VctK6CRneouyfg+GFVvdoMfZXjuCr3HNTe7nfPLStMD0lhY4P7HWHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-05T16:59:20Z"
  mac: ENC[AES256_GCM,data:ECRYbPf6QKHnw5A35PfrWeCr4HZBZJ8iR9sJfsg+Iiw8eIFsLbB7da+Cq2gIXweFoIDLm3BhAElCl/aW1gKQOxNHCovyN4kC9QgmwxKzQOf1/jLOO008eUInbnXaSwGixdm/AypHPdk/vcld0FShKIpJ42TvWhfDtcb5leWGYkg=,iv:kRDP4guBbf0ufCA6RTFF1rJ2Ayo+uf/sWIkWA2GzaCQ=,tag:5z4+RBTpM+zT4JoL+NbmpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
