apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ShELNi8d6laT0Q==,iv:zUfSeDr+ui+bunHg5qN4dIsc5A1lsYn5UF6LFQ4IQwc=,tag:KA1vuaTqa3RVxW02uPPdqw==,type:str]
sops:
  age:
    - recipient: age1205h2v4h4rvx0hfew4uemlrfjnnpfccxj7l9r2ycxdcc92r48dksefc88c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVmpXSTNWS3RwL0JqYmtq
        SStGZWcycDBYSEkyT2YrQXVWbkRESnBFbGdBCmFObkkxZkc5SEdjb0FVUEVIclFH
        UDR1UTNqaWVONStScjRaRkE2V2NxblUKLS0tIDZLMGlZMU4zamJneVVtWlFLMTUr
        OW9INFFqc0tZNU1CVEExdUxGenhmZm8KsI+N/tBECSBbl0Bg2v/ISxOFMAp17Rei
        s6Enqi06ThGmZH/J9N1Obz7J1nA6XpuuEPUtCmKJW43VKUEqUr14Pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-05T17:02:18Z"
  mac: ENC[AES256_GCM,data:iE6g3Od7v3YCmpxSzV/QPuOpOoSHc4NJIDDlqsOvWgEJTiB0rSX49eUcpNEeRJqQRoGX96hOqTgwzkVvzSqfNtz3vUTOWHw8UYUIatBxy/OaQ3aPyoUu385wZu5b1Il6rAmzWeh+FdyYcntLb8zUarc20W0GTQ2D+t12rdVFFKQ=,iv:Ff27Y97k8dnuuUt2y/whtt84sGp16ZaFHefDf4iTuus=,tag:ldnS8RzTq5Yur9PvDcnh3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
