apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:QR1Xi6SCpf3Eng==,iv:FBbuz4li9NRT2/oePws9zNioha1s0aJH5xqfeiJnV7Y=,tag:Z0wrBKMjdDjkMUziRa81IQ==,type:str]
sops:
  age:
    - recipient: age1205h2v4h4rvx0hfew4uemlrfjnnpfccxj7l9r2ycxdcc92r48dksefc88c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UmdaeC9sRFBXS21TUGFI
        UGYraHQwUlJHYWVURDdHY1hqVzgxOGx0QXdzCkpPZWM1eGZFMHVCQW9vcnNoRWlT
        blJwUkZGTmxHUFROYk9xNmhuZFBTTGcKLS0tIDJBMjF2OVhESWMxSDFJNk5yM3RH
        TlFaVzhWYkdza3ZTL0g5THlhQ2dyNnMKMl5pEkIMs2GvFuKztA4iyjowJS5zUXO9
        axTo28nJnbvBU0jDVBDlcrVPZklpsRvkCCAD0Zzp+kFDUjtFXheOQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-05T16:59:20Z"
  mac: ENC[AES256_GCM,data:Dbu+lIE1f/UOg+bSqJarWOIDMEc6pyeJ3MqKlqLnUZv0afWHsAep8KMeiQbkQKFhMNS1AXtTBUDvxKI84XiGeum0ZizD6nvKq//47hV0oaM7gRYE90sTHPKEeSv8ufZhiObma4RUkMPJY2OTHLWBU1Pe/JGYhZgZ9r+cNKiLi0Y=,iv:mBxsn2myjkjXD4dK221mErwmyaA4uw8ilBnOwQutj6E=,tag:s1YhvkmAJuc82c3Rz7xj/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
