apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:g/+ZcYmB3B56nNVqNdKhsFqW8owjozmhE5R5N7fQZouXFGU5ZESONEpiVJqKCLGhg3tgFJS1p9lUH5BA56TcJ4AREEmeFVotP9k=,iv:GJJOf+Ye6WnmTIyCdk5MRNqcEYRcefNrhl5F3T9hgIQ=,tag:/cl6tw4CqGhnXJGwccZgqQ==,type:str]
sops:
  age:
    - recipient: age1205h2v4h4rvx0hfew4uemlrfjnnpfccxj7l9r2ycxdcc92r48dksefc88c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdml2Ty9IOEloU1RCSHRv
        czJCN2Nvb25JVDAycnlaN1Fvam82a0FnWXgwCitLREdHVjVDN3VUV1cxcUlZeVNz
        WmI1ODJEOE9vNWM0SzZaVWszY2RYRDAKLS0tIHhjN01RSHhDZkJDblQ1U3h6T2pk
        aTRqUkpQUE5qUFo3c01OQ3dvRHBwd2sKuud5PPFWOBG6vmbf85y7WtwsZlSh6ros
        sCXIrUkZZ4txR2FL7srJnMjv81NtngvZnaGG3PzTmGa7EBD9FuFrMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-05T17:02:18Z"
  mac: ENC[AES256_GCM,data:DBogEb5oDoaAPUa7DJXwbuEFTCIEK3xIAMPxtyEdC0nw13KvSP+n9WqH02DFA48aQ7qa/v/2tYKc9R45ZSs3ihxmH5ngOwNcr4hr+dmVmwLbJhpAG1g4Qt6fJLMAkPPQVLFAZsbh5Y5rZrcIvTz7okRQYhrIsMAz08WtF6LFSac=,iv:5UW286EcvHyDMwwqnOLCG1oR/pnNHCy1g/HFn4A+ff8=,tag:HsCb+u1Fp50GbZkOnBTDVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
